packages:
  # Frontend applications
  - 'apps/*'
  
  # Shared packages
  - 'packages/*'
  
  # Backend services
  - 'services/*'
  
  # Legacy packages (will be migrated)
  - 'chefshot'
  - 'test-kitchen'
  - 'chef-agent'
  
  # Infrastructure configuration
  # - 'infra/*'  # Uncomment when needed
